<a href="https://colab.research.google.com/github/alegouvea75/Projeto-Avaliativo-final-Modulo1/blob/main/Projeto_Avaliativo_semana_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto Avaliativo final
#Importando as bibliotecas
#Data set: App de vendas previsão dos clientes que estão abandonando a plataforma.Prever se beneficio para manter cliente e valido financeiramente.

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# Configuração estética  dos gráficos
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = [10, 6]

#Leitura dos dados cvs.
#Importando gdown para baixar o arquivo do Google Drive.
#Extrair a ID e lê o arquivo.

In [9]:
import gdown
url_base = 'https://drive.google.com/file/d/1Gcdv7zg4BDquToRBdRwIDksHicJPO0dd/view?usp=sharing'
output_filename = 'ecommerce_churn.csv'
gdown.download(url_base, output_filename, quiet=False, fuzzy=True)
df = pd.read_csv(output_filename)

Downloading...
From: https://drive.google.com/uc?id=1Gcdv7zg4BDquToRBdRwIDksHicJPO0dd
To: /content/ecommerce_churn.csv
100%|██████████| 482k/482k [00:00<00:00, 112MB/s]

## Análise Exploratória de Dados (EDA)
#Conhecer os dados colunas, linhas e estatiticas. O head da base.

In [10]:
print(f"\n1. Dimensões do Dataset: {df.shape[0]} linhas e {df.shape[1]} colunas.")

print("\n2. Visualizando a estrutura inicial dos dados:")
display(df.head(5))

print("\n3. Resumo Estatístico das Variáveis Numéricas:")
display(df.describe())

1. Dimensões do Dataset: 5630 linhas e 20 colunas.

2. Visualizando a estrutura inicial dos dados:

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,160
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,121
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,130

3. Resumo Estatístico das Variáveis Numéricas:

,CustomerID,Churn,Tenure,CityTier,WarehouseToHome,HourSpendOnApp,NumberOfDeviceRegistered,SatisfactionScore,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
count,5630.000000,5630.000000,5366.000000,5630.000000,5379.000000,5375.000000,5630.000000,5630.000000,5630.000000,5630.000000,5365.000000,5374.000000,5372.000000,5323.000000,5630.000000
mean,52815.500000,0.168384,10.189899,1.654707,15.639896,2.931535,3.688988,3.066785,4.214032,0.284902,15.707922,1.751023,3.008004,4.543491,177.221492
std,1625.385339,0.374240,8.557241,0.915389,8.531475,0.721926,1.023999,1.380194,2.583586,0.451408,3.675485,1.894621,2.939680,3.654433,49.193869
min,50001.000000,0.000000,0.000000,1.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,11.000000,0.000000,1.000000,0.000000,0.000000
25%,51408.250000,0.000000,2.000000,1.000000,9.000000,2.000000,3.000000,2.000000,2.000000,0.000000,13.000000,1.000000,1.000000,2.000000,146.000000
50%,52815.500000,0.000000,9.000000,1.000000,14.000000,3.000000,4.000000,3.000000,3.000000,0.000000,15.000000,1.000000,2.000000,3.000000,163.000000
75%,54222.750000,0.000000,16.000000,3.000000,20.000000,3.000000,4.000000,4.000000,6.000000,1.000000,18.000000,2.000000,3.000000,7.000000,196.000000
max,55630.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,26.000000,16.000000,16.000000,46.000000,325.000000

#